[tool.poetry]
name = "html-to-shpaml"
version = "0.1.0"
description = ""
authors = ["Steven Goh"]

[tool.poetry.dependencies]
python = "^3.7"
bs4 = "^0.0.1"
"manage.py" = "^0.2.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
